const websites = [
    "https://virtual.bbcmic.ro/?disc1=elite.ssd&autoboot",
    "https://www.wikipedia.org/",
    "https://codepen.io/p0waqqatsi/full/MWdYLaW",
    "https://www.youtube.com/embed/nt6ab7BTlgE",
    "https://open.spotify.com/embed/track/0Vfgpl5VpDBQexEPYUqaQK?utm_source=generator",
    "https://en.wikipedia.org/wiki/Rust_(programming_language)",
    "https://36days.reflektor.digital/letter/9",
    "https://gorescript.github.io/classic/play/",
    "http://idflood.github.io/ThreeNodes.js/index_optimized.html",
    "https://www.mapstd.com/",
    "http://webglsamples.org/imagesphere/imagesphere.html",
    "https://puginarug.com/",
    "https://binarypiano.com/",
    "https://checkbox.toys/scale/",
    "https://mondrianandme.com/",
    "https://cursoreffects.com/",
    "https://floatingqrcode.com/",
    "https://longdogechallenge.com/",
    "https://hooooooooo.com/",
    "http://corndog.io/",
    "https://onesquareminesweeper.com/",
    "http://www.staggeringbeauty.com/",
    "https://thatsthefinger.com/",
    "https://clicking.toys/flip-grid/neat-nine/3-holes/",
    "https://burymewithmymoney.com/",
    "http://eelslap.com/",
    "https://cant-not-tweet-this.com/",
    "https://theuselessweb.com/"
]

export default websites